language: python
python:
  - "3.4"
branches:
  only:
    - master
    - develop
install:
  - pip install -v pyhamcrest
  - pip install -v coveralls
  - pip install -v Django
  - pip install -v beautifulsoup4
  - pip install -v GoogleMaps
before_script:
  - export PYTHONPATH='.'
script:
  - coverage run --source=polls manage.py test polls
  - coverage run --source=tenders manage.py test tenders
after_success:
  - coveralls
